import LeanAPAP.Extras.BSG
import LeanAPAP.FiniteField.Basic
import LeanAPAP.Mathlib.Algebra.Algebra.Basic
import LeanAPAP.Mathlib.Algebra.BigOperators.Pi
import LeanAPAP.Mathlib.Algebra.Group.AddChar
import LeanAPAP.Mathlib.Algebra.Order.Field.Basic
import LeanAPAP.Mathlib.Algebra.Order.Module.Defs
import LeanAPAP.Mathlib.Analysis.InnerProductSpace.PiL2
import LeanAPAP.Mathlib.Analysis.NormedSpace.PiLp
import LeanAPAP.Mathlib.Combinatorics.Additive.AP.Three.Convolution
import LeanAPAP.Mathlib.Data.Fintype.Pi
import LeanAPAP.Mathlib.Data.NNRat.Defs
import LeanAPAP.Mathlib.Data.Rat.Cast.Defs
import LeanAPAP.Mathlib.Data.Rat.Cast.Lemmas
import LeanAPAP.Mathlib.Data.ZMod.Basic
import LeanAPAP.Mathlib.Tactic.Positivity
import LeanAPAP.Physics.AlmostPeriodicity
import LeanAPAP.Physics.DRC
import LeanAPAP.Physics.Unbalancing
import LeanAPAP.Prereqs.AddChar.Basic
import LeanAPAP.Prereqs.AddChar.Circle
import LeanAPAP.Prereqs.AddChar.PontryaginDuality
import LeanAPAP.Prereqs.Bohr.Basic
import LeanAPAP.Prereqs.Bohr.Regular
import LeanAPAP.Prereqs.Chang
import LeanAPAP.Prereqs.Curlog
import LeanAPAP.Prereqs.Cut
import LeanAPAP.Prereqs.Density
import LeanAPAP.Prereqs.Discrete.Convolution.Basic
import LeanAPAP.Prereqs.Discrete.Convolution.Compact
import LeanAPAP.Prereqs.Discrete.Convolution.Norm
import LeanAPAP.Prereqs.Discrete.Convolution.Order
import LeanAPAP.Prereqs.Discrete.Convolution.WithConv
import LeanAPAP.Prereqs.Discrete.DFT.Basic
import LeanAPAP.Prereqs.Discrete.DFT.Compact
import LeanAPAP.Prereqs.Discrete.LpNorm.Basic
import LeanAPAP.Prereqs.Discrete.LpNorm.Compact
import LeanAPAP.Prereqs.Discrete.LpNorm.Weighted
import LeanAPAP.Prereqs.Dissociation
import LeanAPAP.Prereqs.Energy
import LeanAPAP.Prereqs.Expect.Basic
import LeanAPAP.Prereqs.Expect.Complex
import LeanAPAP.Prereqs.Indicator
import LeanAPAP.Prereqs.LargeSpec
import LeanAPAP.Prereqs.MarcinkiewiczZygmund
import LeanAPAP.Prereqs.Multinomial
import LeanAPAP.Prereqs.Rudin
import LeanAPAP.Prereqs.Translate
import LeanAPAP.Prereqs.WideDiag
