on:
  push:
    branches:
      - master

jobs:
  build_project:
    runs-on: ubuntu-latest
    name: Build project
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install elan
        run: curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y --default-toolchain leanprover/lean4:4.0.0

      - name: Get cache
        run: ~/.elan/bin/lake -Kenv=dev exe cache get

      - name: Build project
        run: ~/.elan/bin/lake -Kenv=dev build LeanAPAP

      - name: Build documentation
        run: ~/.elan/bin/lake -Kenv=dev build LeanAPAP:docs

      - name: Copy documentation
        run: cp -R build/doc docs/

      - name: Remove .gitignore for gh-pages
        run: rm docs/.gitignore

      - name: Bundle dependencies
        uses: ruby/setup-ruby@v1
        with:
          working-directory: docs
          ruby-version: "3.0" # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Bundle website
        working-directory: docs
        run: JEKYLL_ENV=production bundle exec jekyll build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          SINGLE_COMMIT: true
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs/_site
